### ISSUE TITLE
Data feature

### ISSUE THREAD

**Issue by packer-c** [SmallNana/STSGCN_Pytorch#2]
感谢大佬分享的torch框架代码。

有一个小疑问，请问在generate_datasets.py中的第18行里：data = data[:, :, 0:1]  # 只取第一维度的特征

这里 “只取第一维的特征“ 指的是只取 flow 特征吗？是不是这两个数据集里面均包含着三种特征，顺序分别是flow，occupancy，speed？

希望得到您的解答，谢谢！

**Comment by SmallNana** [comment]
> 感谢大佬分享的torch框架代码。
> 
> 有一个小疑问，请问在generate_datasets.py中的第18行里：data = data[:, :, 0:1] # 只取第一维度的特征
> 
> 这里 “只取第一维的特征“ 指的是只取 flow 特征吗？是不是这两个数据集里面均包含着三种特征，顺序分别是flow，occupancy，speed？
> 
> 希望得到您的解答，谢谢！

你好，正如你所想，只取第一维度(亦可以理解为第一个channel)，三个特征分别为total flow, average speed, and average occupancy.

**Comment by packer-c** [comment]
感谢解答！

那么如果想看数据集的具体数字应该如何可视化呢？因为我看数据集是已经转换成了.npz格式了。

**Comment by SmallNana** [comment]
> 感谢解答！
> 
> 那么如果想看数据集的具体数字应该如何可视化呢？因为我看数据集是已经转换成了.npz格式了。

你好，你可以使用 np.load  来加载 .npz格式文件，推荐使用 jupyter 来实现数字可视化

**Comment by packer-c** [comment]
明白啦，非常感谢！代码写的很棒！
